---

- include: check_vars.yml
  tags: 
    - docker

# - include: debian.yml
#  when: ansible_os_family == 'Debian'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: 
    - docker

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: 
    - docker

