---

- include: check_vars.yml
  tags: 
    - docker
    - create
    - docker:create

# - include: debian.yml
#  when: ansible_os_family == 'Debian'

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: 
    - docker
    - create
    - docker:create

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: 
    - docker
    - create
    - docker:create

